# Generated by Django 3.1.7 on 2021-08-02 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20210729_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('age', models.IntegerField()),
                ('disease', models.CharField(max_length=200)),
                ('docname', models.CharField(max_length=200)),
                ('docfee', models.IntegerField(default=500)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 2, 12, 15, 9, 977200))),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
