# Generated by Django 3.1.7 on 2021-08-02 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20210802_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 2, 14, 27, 27, 780943)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=128),
        ),
    ]
