# Generated by Django 3.1.7 on 2021-08-02 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20210802_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 2, 14, 33, 22, 221465)),
        ),
    ]
